apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: grpcserver
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    run: grpcserver
status:
  loadBalancer: {}
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: grpcserver
  name: grpcserver
spec:
  replicas: 1
  selector:
    matchLabels:
      run: grpcserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: grpcserver
    spec:
      containers:
      - image: javierramos1/grpc_server:latest
        name: grpcserver
        ports:
        - containerPort: 50051
        resources: {}
status: {}
